# SPDX-FileCopyrightText: 2022 Daniel Valcour <fosssweeper@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

blank_issues_enabled: true
contact_links:
  - name: Ask a Question
    url: https://github.com/Journeyman-dev/FossSweeper/discussions/categories/q-a
    about: If you wish to ask a question, make a post here.
  - name: Suggest a Feature
    url: https://github.com/Journeyman-dev/FossSweeper/discussions/categories/ideas
    about: If you wish to discuss potential features to be worked on in the future, make a post here.
  - name: Look at our Contributing Guidelines
    url: https://github.com/Journeyman-dev/FossSweeper/blob/main/CONTRIBUTING.md
    about: Please read our project's guidelines here.
  - name: Look at our Code of Conduct
    url: https://github.com/Journeyman-dev/FossSweeper/blob/main/CODE_OF_CONDUCT.md
    about: Please read our standard's of behaviour here.
  - name: Read about Markdown Syntax
    url: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax
    about: Look here for how to format your text with Markdown.
